# NiFi Ansible Playbook
---
- name: NiFi Deployment
  hosts: localhost
  become: false
  vars_files:
    - params.yml
    - ../params.yml

  tasks:
    - name: Docker down for update
      tags: never
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/nifi/"
        state: absent

    - name: Verify NiFi directory exists (vendored in repository)
      tags: always
      ansible.builtin.stat:
        path: "{{ general_vars.digital_twin_folder }}/nifi"
      register: nifi_dir
      failed_when: not nifi_dir.stat.exists or not nifi_dir.stat.isdir

    - name: Create Apache NiFi folders structure
      tags: always
      ansible.builtin.file:
        path: "{{ general_vars.digital_twin_folder }}/nifi/{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"
        recurse: yes
      loop:
        - "nifi/database_repository"
        - "nifi/flowfile_repository"
        - "nifi/content_repository"
        - "nifi/provenance_repository"
        - "nifi/lib"
        - "nifi/python_extensions"
        - "nifi/work"
        - "nifi/nar_extensions"
        - "nifi/state"
        - "nifi/logs"

    - name: Generate Apache NiFi configuration files from templates
      tags: always
      ansible.builtin.template:
        src: "../../nifi/templates/{{ item }}.j2"
        dest: "{{ general_vars.digital_twin_folder }}/nifi/{{ item }}"
        mode: '0644'
      loop: "{{ files_to_fill }}"

    - name: Launch Apache NiFi Docker container
      tags: always
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/nifi/"
        state: present

    - name: Pause for 30 seconds
      tags: always
      ansible.builtin.pause:
        seconds: 30

    - name: Run post-start command inside the container to add NiFi configuration
      tags: always
      community.docker.docker_container_exec:
        container: "{{ general_vars.project_name }}-nifi-nifi-1"
        command: cp -a /tmp/nifi.properties /opt/nifi/nifi-current/conf/nifi.properties

    - name: Restart Apache NiFi container
      tags: always
      community.docker.docker_container:
        name: "{{ general_vars.project_name }}-nifi-nifi-1"
        restart: true
