# Kafka Ansible playbook
---
- name: Kafka Deployment
  hosts: localhost
  become: false
  vars_files:
    - params.yml
    - ../params.yml

  tasks:
    - name: Docker down for update
      tags: never
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/kafka/"
        state: absent

    - name: Verify Kafka directory exists (vendored in repository)
      tags: always
      ansible.builtin.stat:
        path: "{{ general_vars.digital_twin_folder }}/kafka"
      register: kafka_dir
      failed_when: not kafka_dir.stat.exists or not kafka_dir.stat.isdir

    - name: Fill In kafka Configuration Files
      tags: always
      ansible.builtin.replace:
        path: "{{ general_vars.digital_twin_folder }}/kafka/{{ item[0] }}"
        regexp: "(?i:{{ item[1].key }})" # ignore case, match upper and lower without distinction
        replace: "{{ item[1].value }}"
      with_nested:
        - "{{ files_to_fill }}" #for every file in this variable
        - "{{ kafka_cred | dict2items + general_vars | dict2items }}" # for every string in these variables

    - name: Launch Kafka Docker container
      tags: always
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/kafka/"
        state: present
