# Kafka Ansible playbook
---
- name: Kafka Deployment
  hosts: localhost
  become: false
  vars_files:
    - params.yml
    - ../params.yml

  tasks:
    - name: Docker down for update
      tags: never
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/kafka/"
        state: absent

    - name: Verify Kafka directory exists (vendored in repository)
      tags: always
      ansible.builtin.stat:
        path: "{{ general_vars.digital_twin_folder }}/kafka"
      register: kafka_dir
      failed_when: not kafka_dir.stat.exists or not kafka_dir.stat.isdir

    - name: Generate Kafka configuration files from templates
      tags: always
      ansible.builtin.template:
        src: "../../kafka/templates/{{ item }}.j2"
        dest: "{{ general_vars.digital_twin_folder }}/kafka/{{ item }}"
        mode: '0644'
      loop: "{{ files_to_fill }}"

    - name: Launch Kafka Docker container
      tags: always
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/kafka/"
        state: present
