# Kafka Variables
---

files_to_fill: 
  - docker-compose.yml
  - client.config
  - kafka-ui-config.yml

kafka_cred:
  kafka_user: PLCHLD_KFK_USR
  kafka_psw: PLCHLD_KFK_PSW
  kafka_kck_id: PLCHLD_KK_ID # manually added after keycloak configuration
  kafka_kck_scr: PLCHLD_KK_SCR # manually added after keycloak configuration