# NiFi Processors Ansible Playbook
---
- name: NiFi Processors Deployment
  hosts: localhost
  become: false
  vars_files:
    - ../params.yml
    - params.yml

  tasks:
    - name: Copy DQA Validator Files from vendored repository
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ general_vars.digital_twin_folder }}/nifi/nifi/python_extensions/"
      with_fileglob: "vendored/dqa-validator/*.py"

    - name: Copy Schema Validator Files from vendored repository
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ general_vars.digital_twin_folder }}/nifi/nifi/python_extensions/"
      with_fileglob: "vendored/schema-validator/*.py"

    - name: Copy Encapsulator Files from vendored repository
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ general_vars.digital_twin_folder }}/nifi/nifi/python_extensions/"
      with_fileglob: "vendored/unified-data-model-encapsulator/*.py"

    - name: Remove __init__ file
      ansible.builtin.file:
        path: ./__init__.py
        state: absent

    - name: Fill in Apache NiFi configuration files
      ansible.builtin.replace:
        path: "{{ general_vars.digital_twin_folder }}/nifi/nifi/python_extensions/{{ item[0] }}"
        regexp: "(?i:{{ item[1].key }})" # ignore case, match upper and lower without distinction
        replace: "{{ item[1].value }}"
      with_nested:
        - "{{ files_to_fill }}" #for every file in this variable
        - "{{ general_vars | dict2items }}" # for every string in this variable

    - name: Restart Apache NiFi container
      community.docker.docker_container:
        name: "{{ general_vars.project_name }}-nifi-nifi-1"
        restart: true
