# NiFi Variables
---

files_to_fill: 
  - docker-compose.yml
  - nifi.properties

nifi_cred:
  nifi_user: "${NIFI_USER}"
  # PASSWORD LONGER THAN 12 CHARS
  nifi_psw: "${NIFI_PASSWORD}"
  nifi_kck_id: "${NIFI_KEYCLOAK_ID}" # Client ID set in Keycloak
  nifi_kck_scr: "${NIFI_KEYCLOAK_SECRET}" # Secret auto-generated by Keycloak, copy back to .env 