# Quality Reporter Ansible Playbook
---
- name: Quality Reporter Deployment
  hosts: localhost
  become: false
  vars_files:
    - params.yml
    - ../params.yml

  tasks:
    - name: Docker down for update
      tags: never
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/quality_reporter/"
        state: absent

    - name: Verify Quality Reporter directory exists (vendored in repository)
      tags: always
      ansible.builtin.stat:
        path: "{{ general_vars.digital_twin_folder }}/quality_reporter"
      register: quality_reporter_dir
      failed_when: not quality_reporter_dir.stat.exists or not quality_reporter_dir.stat.isdir

    - name: Create Quality Reporter folders structure
      tags: always
      ansible.builtin.file:
        path: "{{ general_vars.digital_twin_folder }}/quality_reporter/{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"
        recurse: yes
      loop:
        - "reporter_data"

    - name: Generate Quality Reporter configuration files from templates
      tags: always
      ansible.builtin.template:
        src: "../../quality_reporter/templates/{{ item }}.j2"
        dest: "{{ general_vars.digital_twin_folder }}/quality_reporter/{{ item }}"
        mode: '0644'
      loop: "{{ files_to_fill }}"

    - name: Launch Quality Reporter Docker container
      tags: always
      community.docker.docker_compose_v2:
        project_src: "{{ general_vars.digital_twin_folder }}/quality_reporter/"
        state: present
